"""Add language

Revision ID: c4759d628e20
Revises: 39022fc15f46
Create Date: 2026-07-24 15:55:38.083298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4759d628e20'
down_revision = '39022fc15f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=20), nullable=False, server_default='python'))
        batch_op.drop_index(batch_op.f('idx_solves_user_date'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'task_types', ['type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('solves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_solves_user_date'), ['user_id', 'created_date'], unique=False)
        batch_op.drop_column('language')

    # ### end Alembic commands ###
