"""drop subject column from tasks

Revision ID: 1069555e7137
Revises: b0949a9cdede
Create Date: 2026-07-12 11:37:08.287364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1069555e7137'
down_revision = 'b0949a9cdede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
