"""Add index on solves for fast distinct counting

Revision ID: 4d42203b19fd
Revises: 1069555e7137
Create Date: 2026-07-13 18:40:30.334007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d42203b19fd'
down_revision = '1069555e7137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solves', schema=None) as batch_op:
        batch_op.create_index('idx_solves_user_task', ['user_id', 'task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solves', schema=None) as batch_op:
        batch_op.drop_index('idx_solves_user_task')

    # ### end Alembic commands ###
