"""Add TestCase model

Revision ID: aae4f46eb93f
Revises: c4e40fa165ad
Create Date: 2026-07-25 12:30:33.477713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae4f46eb93f'
down_revision = 'c4e40fa165ad'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Создаём таблицу test_cases (это у тебя уже было, оставь как есть)
    op.create_table('test_cases',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.Column('input_data', sa.Text(), nullable=False),
        sa.Column('expected_output', sa.Text(), nullable=False),
        sa.Column('order_index', sa.Integer(), nullable=True),
        sa.Column('is_sample', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Индекс для скорости выборки тестов по задаче
    op.create_index(op.f('ix_test_cases_task_id'), 'test_cases', ['task_id'], unique=False)

    # 2. Исправляем таблицу tasks
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        # Меняем тип колонки answer (это ок)
        batch_op.alter_column(
            'answer',
            existing_type=sa.VARCHAR(),
            type_=sa.Text(),
            existing_nullable=True
        )
        
        # Добавляем внешний ключ, НО ТЕПЕРЬ С ИМЕНЕМ!
        batch_op.create_foreign_key(
            'fk_tasks_type_id',  # <-- ВОТ ЭТОГО НЕ ХВАТАЛО
            'task_types',
            ['type_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('answer',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('solves', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'python'"))
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_cases_task_id'))
        batch_op.drop_index(batch_op.f('ix_test_cases_order_index'))

    op.drop_table('test_cases')
    # ### end Alembic commands ###
